
import java.awt.Color;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author terkrub
 */
public class StoreGUI extends javax.swing.JFrame {
    
    UpdateDB update;
    Database db;
    Data data;
    ShowAllProduct view;
    ShowBasket showBasket;
    Basket basket;
    Timer timer;
    /**
     * Creates new form StoreGUI
     * @param db
     * @param data
     * @param update
     */
    public StoreGUI(Database db, Data data, UpdateDB update) {
        initComponents();
        this.update = update;
        this.basket = new Basket();
        this.showBasket = new ShowBasket(data,basket,this);
        this.db = db;
        this.data = data;
        this.view = new ShowAllProduct(data,basket,this);
        this.Depositpanel.setVisible(false);
        this.BasketPanel.setVisible(false);
        this.Checkoutpanel.setVisible(false);
        this.HistoryPanel.setVisible(false);
        this.UserInfo.setText(String.format("Username: %s Money: %.2f $",this.data.username,this.data.money));
        this.ViewBasketB.setText("VIEW BASKET(Total items : "+ basket.totalItems() +")");
        view.showProducts(productpanel);
        

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        HomeB = new javax.swing.JLabel();
        ViewBasketB = new javax.swing.JLabel();
        CheckoutB = new javax.swing.JLabel();
        DepositB = new javax.swing.JLabel();
        HistoryB = new javax.swing.JLabel();
        UserInfoPanel = new javax.swing.JPanel();
        UserInfo = new javax.swing.JLabel();
        LogoutB = new javax.swing.JLabel();
        Homepanel = new javax.swing.JPanel();
        productpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Depositpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        amountF = new javax.swing.JTextField();
        cfDepositB = new javax.swing.JButton();
        Checkoutpanel = new javax.swing.JPanel();
        totalPrice = new javax.swing.JLabel();
        payB = new javax.swing.JButton();
        itemList = new javax.swing.JPanel();
        HistoryPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        BasketPanel = new javax.swing.JPanel();
        basketInfo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(749, 625));

        mainPanel.setBackground(new java.awt.Color(99, 210, 255));

        menupanel.setBackground(new java.awt.Color(99, 210, 255));

        HomeB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HomeB.setForeground(new java.awt.Color(255, 0, 0));
        HomeB.setText("HOME");
        HomeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBMouseClicked(evt);
            }
        });

        ViewBasketB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewBasketB.setForeground(new java.awt.Color(255, 255, 255));
        ViewBasketB.setText("VIEW BASKET(Total items : )");
        ViewBasketB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewBasketBMouseClicked(evt);
            }
        });

        CheckoutB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckoutB.setForeground(new java.awt.Color(255, 255, 255));
        CheckoutB.setText("CHECKOUT");
        CheckoutB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutBMouseClicked(evt);
            }
        });

        DepositB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DepositB.setForeground(new java.awt.Color(255, 255, 255));
        DepositB.setText("DEPOSIT");
        DepositB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositBMouseClicked(evt);
            }
        });

        HistoryB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HistoryB.setForeground(new java.awt.Color(255, 255, 255));
        HistoryB.setText("HISTORY");
        HistoryB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(HomeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(DepositB)
                .addGap(82, 82, 82)
                .addComponent(ViewBasketB)
                .addGap(64, 64, 64)
                .addComponent(CheckoutB)
                .addGap(76, 76, 76)
                .addComponent(HistoryB)
                .addGap(89, 89, 89))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(HomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ViewBasketB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CheckoutB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DepositB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(HistoryB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserInfoPanel.setBackground(new java.awt.Color(99, 210, 255));

        UserInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserInfo.setForeground(new java.awt.Color(255, 255, 255));
        UserInfo.setText("Username: *********  Money: ");

        LogoutB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogoutB.setForeground(new java.awt.Color(255, 255, 255));
        LogoutB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogoutB.setText("LOGOUT  ");
        LogoutB.setVerifyInputWhenFocusTarget(false);
        LogoutB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UserInfoPanelLayout = new javax.swing.GroupLayout(UserInfoPanel);
        UserInfoPanel.setLayout(UserInfoPanelLayout);
        UserInfoPanelLayout.setHorizontalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UserInfoPanelLayout.setVerticalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutB, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        Homepanel.setBackground(new java.awt.Color(99, 210, 255));

        javax.swing.GroupLayout productpanelLayout = new javax.swing.GroupLayout(productpanel);
        productpanel.setLayout(productpanelLayout);
        productpanelLayout.setHorizontalGroup(
            productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productpanelLayout.setVerticalGroup(
            productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PRICE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NAME");

        javax.swing.GroupLayout HomepanelLayout = new javax.swing.GroupLayout(Homepanel);
        Homepanel.setLayout(HomepanelLayout);
        HomepanelLayout.setHorizontalGroup(
            HomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepanelLayout.createSequentialGroup()
                .addGroup(HomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomepanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(HomepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HomepanelLayout.setVerticalGroup(
            HomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomepanelLayout.createSequentialGroup()
                .addGroup(HomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Depositpanel.setBackground(new java.awt.Color(99, 210, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Card Number :4835 **** **** 9830");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("  Expire : 04/2099");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" CCV : ***");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please enter amont you want to deposit");

        jPanel2.setBackground(new java.awt.Color(99, 210, 255));

        amountF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountF, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountF, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        cfDepositB.setText("Comfirm Deposit");
        cfDepositB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfDepositBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DepositpanelLayout = new javax.swing.GroupLayout(Depositpanel);
        Depositpanel.setLayout(DepositpanelLayout);
        DepositpanelLayout.setHorizontalGroup(
            DepositpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addComponent(cfDepositB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DepositpanelLayout.setVerticalGroup(
            DepositpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositpanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cfDepositB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Checkoutpanel.setBackground(new java.awt.Color(99, 210, 255));

        totalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(255, 255, 255));
        totalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPrice.setText("TOTAL PRICE : 0.00 $");

        payB.setText("PAY ALL NOW !!!");
        payB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemListLayout = new javax.swing.GroupLayout(itemList);
        itemList.setLayout(itemListLayout);
        itemListLayout.setHorizontalGroup(
            itemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        itemListLayout.setVerticalGroup(
            itemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CheckoutpanelLayout = new javax.swing.GroupLayout(Checkoutpanel);
        Checkoutpanel.setLayout(CheckoutpanelLayout);
        CheckoutpanelLayout.setHorizontalGroup(
            CheckoutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
            .addComponent(payB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CheckoutpanelLayout.setVerticalGroup(
            CheckoutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckoutpanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(itemList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        HistoryPanel.setBackground(new java.awt.Color(99, 210, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Date", "Amount", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout HistoryPanelLayout = new javax.swing.GroupLayout(HistoryPanel);
        HistoryPanel.setLayout(HistoryPanelLayout);
        HistoryPanelLayout.setHorizontalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        HistoryPanelLayout.setVerticalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryPanelLayout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BasketPanel.setBackground(new java.awt.Color(99, 210, 255));

        javax.swing.GroupLayout basketInfoLayout = new javax.swing.GroupLayout(basketInfo);
        basketInfo.setLayout(basketInfoLayout);
        basketInfoLayout.setHorizontalGroup(
            basketInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        basketInfoLayout.setVerticalGroup(
            basketInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PRICE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NAME");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TOTAL");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AMOUNT");

        javax.swing.GroupLayout BasketPanelLayout = new javax.swing.GroupLayout(BasketPanel);
        BasketPanel.setLayout(BasketPanelLayout);
        BasketPanelLayout.setHorizontalGroup(
            BasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasketPanelLayout.createSequentialGroup()
                .addGroup(BasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasketPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 267, Short.MAX_VALUE))
                    .addGroup(BasketPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(basketInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BasketPanelLayout.setVerticalGroup(
            BasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasketPanelLayout.createSequentialGroup()
                .addGroup(BasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(basketInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Homepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Depositpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Checkoutpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(BasketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Homepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 125, Short.MAX_VALUE)
                .addComponent(UserInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(Depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addContainerGap(204, Short.MAX_VALUE)
                    .addComponent(Checkoutpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(BasketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBMouseClicked
        LoginGUI login = new LoginGUI(db);
        login.setLocationRelativeTo(this);
        this.data.loginFlag = false;
        this.dispose();
    }//GEN-LAST:event_LogoutBMouseClicked

    private void DepositBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositBMouseClicked
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(true);
        this.DepositB.setForeground(Color.RED);
    }//GEN-LAST:event_DepositBMouseClicked

    private void HomeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBMouseClicked
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        view.showProducts(productpanel);
        this.HomeB.setForeground(Color.RED);
        this.Homepanel.setVisible(false);
        this.Homepanel.setVisible(true);
        
        
        
    }//GEN-LAST:event_HomeBMouseClicked

    private void amountFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFActionPerformed

    private void ViewBasketBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBasketBMouseClicked
        // TODO add your handling code here:
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
       
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        showBasket.showItems(basketInfo);
        this.BasketPanel.setVisible(false);
        this.BasketPanel.setVisible(true);
        this.ViewBasketB.setForeground(Color.RED);
    }//GEN-LAST:event_ViewBasketBMouseClicked

    private void CheckoutBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutBMouseClicked
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        showBasket.showItems(itemList);
        this.Checkoutpanel.setVisible(false);
        this.Checkoutpanel.setVisible(true);
        this.CheckoutB.setForeground(Color.RED);
    }//GEN-LAST:event_CheckoutBMouseClicked

    private void HistoryBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryBMouseClicked
        // TODO add your handling code here:
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        new ShowHistory(data).show(jTable3);
        this.HistoryPanel.setVisible(true);
        this.HistoryB.setForeground(Color.RED);
    }//GEN-LAST:event_HistoryBMouseClicked

    private void cfDepositBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfDepositBActionPerformed
        try{
            double amount = Double.parseDouble(amountF.getText());
            this.data.money += amount;
            this.UserInfo.setText(String.format("Username: %s Money: %.2f $",this.data.username,this.data.money));
            data.history.push(new History("Deposit",new Date(),amount,0));
            update.updateMoney();
            update.addHistory("Deposit", new Date(), amount, 0.0);
            JOptionPane.showMessageDialog(null,"Deposit Sucessful !!!","Sucess",JOptionPane.INFORMATION_MESSAGE);
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please enter the amount you want to deposit","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cfDepositBActionPerformed

    private void payBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBActionPerformed
        Checkout check = new Checkout(data,basket);
        if (basket.basket.isEmpty()){
            JOptionPane.showMessageDialog(null,"You do not have anything in basket","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if (!check.payAll(update)) {
            JOptionPane.showMessageDialog(null,"You do not have enought money to buy","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        showBasket.showItems(itemList);
        
        this.UserInfo.setText(String.format("Username: %s Money: %.2f $",this.data.username,this.data.money));
        this.ViewBasketB.setText("VIEW BASKET(Total items : "+ basket.totalItems() +")");
        this.Checkoutpanel.setVisible(false);
        this.Checkoutpanel.setVisible(true);
        this.CheckoutB.setForeground(Color.RED);
        update.updateMoney();
    }//GEN-LAST:event_payBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasketPanel;
    private javax.swing.JLabel CheckoutB;
    private javax.swing.JPanel Checkoutpanel;
    private javax.swing.JLabel DepositB;
    private javax.swing.JPanel Depositpanel;
    private javax.swing.JLabel HistoryB;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JLabel HomeB;
    private javax.swing.JPanel Homepanel;
    private javax.swing.JLabel LogoutB;
    private javax.swing.JLabel UserInfo;
    private javax.swing.JPanel UserInfoPanel;
    public javax.swing.JLabel ViewBasketB;
    private javax.swing.JTextField amountF;
    private javax.swing.JPanel basketInfo;
    private javax.swing.JButton cfDepositB;
    private javax.swing.JPanel itemList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JButton payB;
    private javax.swing.JPanel productpanel;
    public javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
