
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author terkrub
 */
public class StoreGUI extends javax.swing.JFrame {
    
    Database db;
    Data data;
    
    /**
     * Creates new form StoreGUI
     * @param db
     * @param data
     */
    public StoreGUI(Database db, Data data) {
        initComponents();
        this.db = db;
        this.data = data;
        this.Depositpanel.setVisible(false);
        this.BasketPanel.setVisible(false);
        this.Checkoutpanel.setVisible(false);
        this.HistoryPanel.setVisible(false);
        this.UserInfo.setText(String.format("Username: %s Money: %.2f",this.data.username,this.data.money));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        HomeB = new javax.swing.JLabel();
        ViewBasketB = new javax.swing.JLabel();
        CheckoutB = new javax.swing.JLabel();
        DepositB = new javax.swing.JLabel();
        HistoryB = new javax.swing.JLabel();
        UserInfoPanel = new javax.swing.JPanel();
        UserInfo = new javax.swing.JLabel();
        LogoutB = new javax.swing.JLabel();
        Homepanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        Depositpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        amountF = new javax.swing.JTextField();
        cfDepositB = new javax.swing.JButton();
        BasketPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Checkoutpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        totalPrice = new javax.swing.JLabel();
        payB = new javax.swing.JButton();
        HistoryPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(99, 210, 255));

        menupanel.setBackground(new java.awt.Color(99, 210, 255));

        HomeB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HomeB.setForeground(new java.awt.Color(255, 0, 0));
        HomeB.setText("HOME");
        HomeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBMouseClicked(evt);
            }
        });

        ViewBasketB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ViewBasketB.setForeground(new java.awt.Color(255, 255, 255));
        ViewBasketB.setText("VIEW BASKET(Total items : )");
        ViewBasketB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewBasketBMouseClicked(evt);
            }
        });

        CheckoutB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckoutB.setForeground(new java.awt.Color(255, 255, 255));
        CheckoutB.setText("CHECKOUT");
        CheckoutB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutBMouseClicked(evt);
            }
        });

        DepositB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DepositB.setForeground(new java.awt.Color(255, 255, 255));
        DepositB.setText("DEPOSIT");
        DepositB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositBMouseClicked(evt);
            }
        });

        HistoryB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HistoryB.setForeground(new java.awt.Color(255, 255, 255));
        HistoryB.setText("HISTORY");
        HistoryB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(HomeB)
                .addGap(58, 58, 58)
                .addComponent(DepositB)
                .addGap(35, 35, 35)
                .addComponent(ViewBasketB)
                .addGap(28, 28, 28)
                .addComponent(CheckoutB)
                .addGap(44, 44, 44)
                .addComponent(HistoryB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(HomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ViewBasketB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CheckoutB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DepositB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(HistoryB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserInfoPanel.setBackground(new java.awt.Color(99, 210, 255));

        UserInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserInfo.setForeground(new java.awt.Color(255, 255, 255));
        UserInfo.setText("Username: *********  Money: ");

        LogoutB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogoutB.setForeground(new java.awt.Color(255, 255, 255));
        LogoutB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogoutB.setText("LOGOUT  ");
        LogoutB.setVerifyInputWhenFocusTarget(false);
        LogoutB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UserInfoPanelLayout = new javax.swing.GroupLayout(UserInfoPanel);
        UserInfoPanel.setLayout(UserInfoPanelLayout);
        UserInfoPanelLayout.setHorizontalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UserInfoPanelLayout.setVerticalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutB, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        Homepanel.setBackground(new java.awt.Color(99, 210, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Name", "Amount", "Total Price", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout HomepanelLayout = new javax.swing.GroupLayout(Homepanel);
        Homepanel.setLayout(HomepanelLayout);
        HomepanelLayout.setHorizontalGroup(
            HomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        HomepanelLayout.setVerticalGroup(
            HomepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        Depositpanel.setBackground(new java.awt.Color(99, 210, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Card Number :4835 **** **** 9830");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("  Expire : 04/2099");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" CCV : ***");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please enter amont you want to deposit");

        jPanel2.setBackground(new java.awt.Color(99, 210, 255));

        amountF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountF, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountF, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        cfDepositB.setText("Comfirm Deposit");
        cfDepositB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfDepositBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DepositpanelLayout = new javax.swing.GroupLayout(Depositpanel);
        Depositpanel.setLayout(DepositpanelLayout);
        DepositpanelLayout.setHorizontalGroup(
            DepositpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
            .addComponent(cfDepositB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DepositpanelLayout.setVerticalGroup(
            DepositpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositpanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cfDepositB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        BasketPanel.setBackground(new java.awt.Color(99, 210, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Total items", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout BasketPanelLayout = new javax.swing.GroupLayout(BasketPanel);
        BasketPanel.setLayout(BasketPanelLayout);
        BasketPanelLayout.setHorizontalGroup(
            BasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        BasketPanelLayout.setVerticalGroup(
            BasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        Checkoutpanel.setBackground(new java.awt.Color(99, 210, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Total items", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        totalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(255, 255, 255));
        totalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPrice.setText("TOTAL PRICE : 0.00 $");

        payB.setText("PAY ALL NOW !!!");

        javax.swing.GroupLayout CheckoutpanelLayout = new javax.swing.GroupLayout(Checkoutpanel);
        Checkoutpanel.setLayout(CheckoutpanelLayout);
        CheckoutpanelLayout.setHorizontalGroup(
            CheckoutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
            .addComponent(totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(payB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CheckoutpanelLayout.setVerticalGroup(
            CheckoutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckoutpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(payB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        HistoryPanel.setBackground(new java.awt.Color(99, 210, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Date", "Amount", "Total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout HistoryPanelLayout = new javax.swing.GroupLayout(HistoryPanel);
        HistoryPanel.setLayout(HistoryPanelLayout);
        HistoryPanelLayout.setHorizontalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        HistoryPanelLayout.setVerticalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryPanelLayout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Homepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Depositpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BasketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Checkoutpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Homepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 41, Short.MAX_VALUE)
                .addComponent(UserInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(Depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addContainerGap(81, Short.MAX_VALUE)
                    .addComponent(BasketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(Checkoutpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HistoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBMouseClicked
        LoginGUI login = new LoginGUI(db);
        login.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_LogoutBMouseClicked

    private void DepositBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositBMouseClicked
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(true);
        this.DepositB.setForeground(Color.RED);
    }//GEN-LAST:event_DepositBMouseClicked

    private void HomeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBMouseClicked
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        this.Homepanel.setVisible(true);
        this.HomeB.setForeground(Color.RED);
    }//GEN-LAST:event_HomeBMouseClicked

    private void amountFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFActionPerformed

    private void ViewBasketBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBasketBMouseClicked
        // TODO add your handling code here:
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
       
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(true);
        this.ViewBasketB.setForeground(Color.RED);
    }//GEN-LAST:event_ViewBasketBMouseClicked

    private void CheckoutBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutBMouseClicked
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(false);
        this.HistoryB.setForeground(Color.white);
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(true);
        this.CheckoutB.setForeground(Color.RED);
    }//GEN-LAST:event_CheckoutBMouseClicked

    private void HistoryBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryBMouseClicked
        // TODO add your handling code here:
        this.Homepanel.setVisible(false);
        this.HomeB.setForeground(Color.white);
        
        this.BasketPanel.setVisible(false);
        this.ViewBasketB.setForeground(Color.white);
        
        this.Checkoutpanel.setVisible(false);
        this.CheckoutB.setForeground(Color.white);
        
        
        this.Depositpanel.setVisible(false);
        this.DepositB.setForeground(Color.white);
        
        this.HistoryPanel.setVisible(true);
        this.HistoryB.setForeground(Color.RED);
    }//GEN-LAST:event_HistoryBMouseClicked

    private void cfDepositBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfDepositBActionPerformed
        try{
            double amount = Double.parseDouble(amountF.getText());
            this.data.money += amount;
            this.UserInfo.setText(String.format("Username: %s Money: %.2f",this.data.username,this.data.money));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please enter the amount you want to deposit","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cfDepositBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasketPanel;
    private javax.swing.JLabel CheckoutB;
    private javax.swing.JPanel Checkoutpanel;
    private javax.swing.JLabel DepositB;
    private javax.swing.JPanel Depositpanel;
    private javax.swing.JLabel HistoryB;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JLabel HomeB;
    private javax.swing.JPanel Homepanel;
    private javax.swing.JLabel LogoutB;
    private javax.swing.JLabel UserInfo;
    private javax.swing.JPanel UserInfoPanel;
    private javax.swing.JLabel ViewBasketB;
    private javax.swing.JTextField amountF;
    private javax.swing.JButton cfDepositB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JButton payB;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
